name: deploy_backend
# deploy when push is made to backend folder.

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build with dotnet
      run: dotnet build backend/api/api.csproj --configuration Release

    - name: Publish with dotnet
      run: dotnet publish backend/api/api.csproj --configuration Release --output ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set runtime version to v4
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set --name getresumefunctionapp --resource-group azureresume-rg --settings "FUNCTIONS_EXTENSION_VERSION=~4" "FUNCTIONS_WORKER_RUNTIME=dotnet"

    - name: Set .NET version to 8
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config set --name getresumefunctionapp --resource-group azureresume-rg --linux-fx-version "DOTNET|8.0"
      continue-on-error: true

    - name: Stop Function App before deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp stop --name getresumefunctionapp --resource-group azureresume-rg

    - name: Create deployment package
      run: |
        cd ./publish
        zip -r ../deploy.zip .
        cd ..

    - name: Deploy to Azure Functions using zip deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp deployment source config-zip --resource-group azureresume-rg --name getresumefunctionapp --src deploy.zip --build-remote false

    - name: Start Function App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp start --name getresumefunctionapp --resource-group azureresume-rg

    - name: logout
      run: |
            az logout
      if: always()
